### ISSUE TITLE
Replace unicode to LaTex infrastructure

### ISSUE THREAD

**Issue by schlaicha** [schlaicha/jupyter-publication-scripts#1]
There is a nice package available at https://gitcafe.com/yuexue/unicode_tex/ which we should incorporate in `pre_cite2c.py` instead of maintaining our own list there.

**Comment by jcfschulz** [comment]
Added a first commit including this functionality. I updated the example to include a certain slovenian name that included characters problematic in BibTeX. Everything works nicely...
However, the unicode_tex module has one problem, it also converts the space to "\space" without a trailing space, which in return can occasionally screw up bibtex. I put a copy of this module in here with the space removed. We should probably send a pull request with that to the original module. However, I think the space should never be replaced here, this would be weird...
