### ISSUE TITLE
unify licences

### ISSUE THREAD

**Issue by jcfschulz** [schlaicha/jupyter-publication-scripts#2]
Currently we have almost no proper licence texts in the sources. Change them all to the licence from Jupyter!

**Comment by schlaicha** [comment]
I guess it is fine to put a reasonable license into the corresponding license file only? Any thoughts on that?

**Comment by jcfschulz** [comment]
I think we should have something like in pre_cite2c.py, where I stated, that this would be licenced under the modified BSD licence and then have the actual licence in a specific licence file.

**Comment by schlaicha** [comment]
Just wonder as e.g. Jupyter only has the license file...
Guess this is a matter of taste.

**Comment by jcfschulz** [comment]
I shortly updated the licence file just so we get rid of GPL quickly

**Comment by schlaicha** [comment]
Only GPL requires you to put the license into every source file.
According to https://help.github.com/articles/open-source-licensing/ it is perfectly fine to have just a LICENSE file. Therefore we should unify our files correspondingly and put all copyright holder into this file and remove the redundant information from the source files.

**Comment by schlaicha** [comment]
implemented in b944bf7
