### ISSUE TITLE
custom LaTeX preamble

### ISSUE THREAD

**Issue by PicoCentauri** [schlaicha/jupyter-publication-scripts#5]
Dear jupyter-publication-scripts-Team,

it would be nice to add a custom LaTeX preamble to add extra packages and definitions.

Thanks a lot.

**Comment by schlaicha** [comment]
We have inheritance-based tplx files on the long term, so adding something there should be straight forward. However, fancy definitions and packages won't help as also the javascript counterpart should know about them.

Please provide some comments ideas, otherwise I propose the problem as wontfix.

**Comment by PicoCentauri** [comment]
I think the easiest way is just that the user can add a preambel.tex in the notebooks directoy and if there is one it is simply added to the tex file using \include{preambel.tex}

**Comment by schlaicha** [comment]
As long as there is no support inside Javascript/Markdown to use LaTex extensions, the only way is to inherit a corresponding `tplx`-file and add your personal templates there.
