### ISSUE TITLE
Let cite2c preprocessor also create bibliography in html export

### ISSUE THREAD

**Issue by jcfschulz** [schlaicha/jupyter-publication-scripts#6]
What is the correct way to get output format of nbconvert?

**Comment by schlaicha** [comment]
Sorry, I don't think I get your question completely. You don't talk about the nbcnvert --to html feature I guess... So are you interested in raw nbconvert?

**Comment by jcfschulz** [comment]
The way to distinguish the output type is using the `resources["output_extension"]` item, it is `.tex` for latex and pdf and `.html` for html export.

**Comment by jcfschulz** [comment]
fixed in e42a576
We now have citeproc and unicode_tex as dependencies. 
@schlaicha maybe you can modify the installer accordingly

**Comment by schlaicha** [comment]
dependencies added in 2356050
