### ISSUE TITLE
Improve handling of external figures in nbconvert to pdf

### ISSUE THREAD

**Issue by schlaicha** [schlaicha/jupyter-publication-scripts#7]
A nice way to include external figures in a notebook is e.g.

```
from IPython.display import Image
Image(filename='test.png')
```

However, that way we still have the `[out]` block present in the LaTeX file.

Is there any nicer way of handling figures? Otherwise we should modify the LaTeX preprocessors correspondingly.

**Comment by jcfschulz** [comment]
fixed in f481e701cc4a40e3f6917b599da2dd87a3acb874
