### ISSUE TITLE
Make bibtex work for direct conversion to pdf

### ISSUE THREAD

**Issue by jcfschulz** [schlaicha/jupyter-publication-scripts#9]
When nbconvert is called with --to=pdf bibtex is not called, although according to documentary this should work automatically... Investigate and fix :)

**Comment by jcfschulz** [comment]
Made a small change to the bibtex preprocessesor so that the pdf exporter is in principle able to run with bibtex. 
However until this [issue](https://github.com/jupyter/nbconvert/pull/194) is addressed, it will not work out of the box.

So fixed in 6c02af7c336e93aaa750cb28568482ab8a378196 but postponed until upstream bug is fixed...

**Comment by schlaicha** [comment]
Did you mess up the link to the bibtex preprocessor issue? Would be great to have the right one here for reference...

**Comment by jcfschulz** [comment]
Sorry, was the wrong one of course, it is fixed now.

**Comment by jcfschulz** [comment]
Since bug is fixed upstream, I will close this. Don't know however, when this bugfix will propagate through pip etc. So manual fixing the bug as [in](https://github.com/jcfschulz/nbconvert/commit/2c24daac1fff748a752746f27a28bd2300f2f1ff) might be necessary...
